Repository db0/pythorhead, pull requests merged in 2023-07, with the labels that each got.

#40 CI: Added announcement in !pythorhead@lemmy.dbzer0.com
  .github/publish_on_lemmy.py
  .github/workflows/pypi.yml
Labels: release:patch

#37 Enum for languages
  pythorhead/comment.py
  pythorhead/community.py
  pythorhead/post.py
  pythorhead/site.py
  pythorhead/types/__init__.py
  pythorhead/types/language.py
Labels: release:patch

#43 added function for subscribing and unsubscribing
  pythorhead/community.py
Labels: release:minor

#44 Purge for Communities, Comments, Posts and Users
  examples/pic.py
  pythorhead/comment.py
  pythorhead/community.py
  pythorhead/post.py
  pythorhead/user.py
Labels: release:minor

#47 feat: marks PM as read
  pythorhead/private_message.py
Labels: release:patch

#48 Add "Add mod to community"
  pythorhead/community.py
Labels: release:patch

#51 fix: avoid crashing when language not set
  pythorhead/site.py
Labels: release:patch

#53 Implemented search
  pythorhead/lemmy.py
Labels: release:minor

#54 Add admin class & list applications admin function
  pythorhead/admin.py
  pythorhead/lemmy.py
Labels: release:minor

#58 Fix community.list
  pythorhead/community.py
  pythorhead/types/listing.py
  pythorhead/types/sort.py
Labels: release:patch

#60 Fix community list by type
  pythorhead/comment.py
Labels: release:patch

#62 Allow sending of TOTP token with login request
  pythorhead/lemmy.py
  pythorhead/requestor.py
Labels: enhancement, release:patch

#63 Functionallity to distinguish comments.
  pythorhead/comment.py
Labels: release:patch
